# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Felipe\Desktop\APS Processamento de Imagem e Visão Computacional\loginUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(600, 550)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setStyleSheet("font: 12pt \"Poppins\";")
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(280, 80, 61, 31))
        self.label_login.setObjectName("label_login")
        self.lineEdit_user = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_user.setGeometry(QtCore.QRect(99, 130, 431, 40))
        self.lineEdit_user.setStyleSheet("background-color: white;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"color: black;\n"
"font: 25 9pt \"Poppins ExtraLight\";\n"
"")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setReadOnly(False)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(99, 190, 431, 40))
        self.lineEdit_password.setStyleSheet("background-color: white;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"color: black;\n"
"font: 25 9pt \"Poppins ExtraLight\";\n"
"")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setReadOnly(False)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.btn_acessar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_acessar.setGeometry(QtCore.QRect(240, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_acessar.setFont(font)
        self.btn_acessar.setStyleSheet("QPushButton#btn_acessar{\n"
"background-color: rgb(131, 198, 131);\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding:5px;\n"
"font-size:18px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btn_acessar:hover{\n"
"    \n"
"    background-color: rgb(105, 198, 127);\n"
"}")
        self.btn_acessar.setObjectName("btn_acessar")
        self.loginInvalido = QtWidgets.QLabel(self.centralwidget)
        self.loginInvalido.setGeometry(QtCore.QRect(100, 360, 431, 31))
        self.loginInvalido.setStyleSheet("font: 9pt \"Poppins\";")
        self.loginInvalido.setText("")
        self.loginInvalido.setAlignment(QtCore.Qt.AlignCenter)
        self.loginInvalido.setObjectName("loginInvalido")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 440, 221, 20))
        self.label.setStyleSheet("font: 9pt \"Poppins\";")
        self.label.setObjectName("label")
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 42))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_login.setText(_translate("Form", "Login"))
        self.lineEdit_user.setPlaceholderText(_translate("Form", "Usuário"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "Senha"))
        self.btn_acessar.setText(_translate("Form", "Acessar"))
        self.label.setText(_translate("Form", "Ministério do Meio Ambiente"))
